Repository lineupjs/lineupjs, pull requests merged in 2019-12, with the labels that each got.

#213 Revert D3 dependencies for LineUp v4
  package.json
Labels: lineup: v4, type: technical debt

#215 Limit export to `toCategories()` only
  src/model/index.ts
Labels: lineup: v4, type: refactor

#211 Fix values in array column and use correct labels
  demo/boxplot.html
  demo/multivalue.html
  src/builder/column/NumberColumnBuilder.ts
  src/model/NumbersColumn.ts
  src/renderer/BoxplotCellRenderer.ts
Labels: lineup: v4, priority: medium, release: patch, type: bug
