Repository lineupjs/lineupjs, pull requests merged in 2019-11, with the labels that each got.

#201 Use font-variant-numeric
  src/styles/renderer/_bar.scss
  src/styles/renderer/_rank.scss
Labels: lineup: v3, release: patch, type: feature

#186 Use font-variant-numeric
  src/styles/renderer/_bar.scss
  src/styles/renderer/_rank.scss
Labels: lineup: v4, release: patch, type: feature

#199 Regular expression based text filter bug
  src/model/StringColumn.ts
  src/ui/dialogs/StringFilterDialog.ts
Labels: lineup: v3, release: patch, type: bug

#198 Regular expression based text filter bug
  src/model/StringColumn.ts
  src/ui/dialogs/StringFilterDialog.ts
Labels: lineup: v4, release: patch, type: bug

#204 Make renderer and utils function publicly available (i.e., remove @internal markers)
  src/renderer/AAggregatedGroupRenderer.ts
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/ActionRenderer.ts
  src/renderer/AggregateGroupRenderer.ts
  src/renderer/AnnotationRenderer.ts
  src/renderer/BarCellRenderer.ts
  src/renderer/BooleanCellRenderer.ts
  src/renderer/BoxplotCellRenderer.ts
  src/renderer/BrightnessCellRenderer.ts
  src/renderer/CategoricalCellRenderer.ts
  src/renderer/CategoricalHeatmapCellRenderer.ts
  src/renderer/CategoricalStackedDistributionlCellRenderer.ts
  src/renderer/CircleCellRenderer.ts
  src/renderer/DotCellRenderer.ts
  src/renderer/GroupCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/ImageCellRenderer.ts
  src/renderer/InterleavingCellRenderer.ts
  src/renderer/LinkCellRenderer.ts
  src/renderer/LinkMapCellRenderer.ts
  src/renderer/LoadingCellRenderer.ts
  src/renderer/MapBarCellRenderer.ts
  src/renderer/MultiLevelCellRenderer.ts
  src/renderer/RankCellRenderer.ts
  src/renderer/SelectionRenderer.ts
  src/renderer/SparklineCellRenderer.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/TableCellRenderer.ts
  src/renderer/UpSetCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/renderer/utils.ts
Labels: lineup: v3, release: minor

#193 Group by string value in StringColumn
  demo/string_grouping.html
  src/model/StringColumn.ts
  src/ui/dialogs/groupString.ts
Labels: lineup: v3, release: minor

#191 Fix number filter by comparing the min / max values to the domai…
  demo/small_numbers.html
  src/renderer/HistogramCellRenderer.ts
Labels: lineup: v3, release: patch

#189 Fix number filter by comparing the min / max values to the domai…
  demo/small_numbers.html
  src/renderer/HistogramCellRenderer.ts
Labels: lineup: v4, release: patch
