Repository lineupjs/lineupjs, pull requests merged in 2020-03, with the labels that each got.

#245 Set title prop in StringCellRenderer
  src/renderer/StringCellRenderer.ts
Labels: lineup: v3, release: minor, type: feature

#246 Set title prop in StringCellRenderer
  src/renderer/StringCellRenderer.ts
Labels: lineup: v4, release: minor, type: feature

#238 Clear aggregation and update group column accordingly
  src/renderer/AggregateGroupRenderer.ts
Labels: lineup: v4

#252 Fix removal of filtered column
  src/model/CompositeColumn.ts
  src/model/Ranking.ts
Labels: lineup: v3

#241 Fix canvas horizontal shift issue
  demo/wide.html
  src/ui/EngineRanking.ts
Labels: lineup: v4

#256 Add aggregation method hint to tooltip
  src/internal/utils.ts
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/ui/dialogs/utils.ts
Labels: lineup: v4

#253 Use lodash.get() for complex accessor
  demo/complex_accessor.html
  package-lock.json
  package.json
  src/builder/adapter/column.ts
  src/builder/column/CategoricalColumnBuilder.ts
  src/builder/column/NumberColumnBuilder.ts
  src/internal/accessor.ts
  src/provider/ACommonDataProvider.ts
  src/provider/utils.ts
  tests/internal/accessor.spec.ts
Labels: lineup: v3

#254 Use lodash.get() for complex accessor
  demo/complex_accessor.html
  package-lock.json
  package.json
  src/builder/adapter/column.ts
  src/builder/column/CategoricalColumnBuilder.ts
  src/builder/column/NumberColumnBuilder.ts
  src/internal/accessor.ts
  src/internal/index.ts
  src/provider/ACommonDataProvider.ts
  src/provider/utils.ts
  tests/internal/accessor.spec.ts
  typeGen/ts27/tsconfig.json
Labels: lineup: v4

#255 Add subtitle / summary to column headers
  demo/subtitle_summary.html
  src/builder/column/ColumnBuilder.ts
  src/model/Column.ts
  src/model/interfaces.ts
  src/styles/engine/_header.scss
  src/styles/header/_index.scss
  src/styles/panel/_entry.scss
  src/ui/EngineRanking.ts
  src/ui/MultiLevelRenderColumn.ts
  src/ui/RenderColumn.ts
  src/ui/dialogs/RenameDialog.ts
  src/ui/header.ts
  src/ui/panel/SidePanelEntryVis.ts
Labels: lineup: v4

#259 Fix grouping of previously ungrouped column by matching the nested header
  src/ui/MultiLevelRenderColumn.ts
Labels: lineup: v4

#240 Use number format of column in interactive summary
  src/model/CompositeNumberColumn.ts
  src/model/INumberColumn.ts
  src/model/NumberColumn.ts
  src/renderer/HistogramCellRenderer.ts
  src/styles/renderer/_histogram.scss
Labels: lineup: v3

#264 Fix undefined sublabel in `updateHeader()`
  src/ui/header.ts
Labels: release: patch, type: bug

#268 Switch order of `color` and `colorMapping` in `restoreColorMapping()`
  src/model/ColorMappingFunction.ts
Labels: lineup: v3, type: bug

#239 Use number format of column in interactive summary
  src/renderer/HistogramCellRenderer.ts
  src/renderer/histogram.ts
  src/styles/_vars.scss
  src/styles/renderer/_histogram.scss
Labels: lineup: v4

#260 LineUp v4 testing demo
  demo/all_column_types.html
Labels: lineup: v4, release: minor, type: feature

#266 avoid toolbar side effects
  src/model/internal.ts
  src/ui/EngineRenderer.ts
  src/ui/interfaces.ts
  src/ui/toolbar.ts
Labels: lineup: v4

#271 Remove warning message by using `colorMapping` property in `deriveColors()`
  src/provider/utils.ts
Labels: release: patch

#273 Sort categorical groups similar to sort values
  src/model/internalCategorical.ts
Labels: lineup: v4, release: minor, type: feature

#267 Improve customization of column types, toolbar actions and dialogs
  demo/custom_column.html
  src/builder/LineUpBuilder.ts
  src/builder/adapter/lineup.ts
  src/config.ts
  src/model/AggregateGroupColumn.ts
  src/model/BooleanColumn.ts
  src/model/BooleansColumn.ts
  src/model/BoxPlotColumn.ts
  src/model/CategoricalColumn.ts
  src/model/CategoricalMapColumn.ts
  src/model/CategoricalsColumn.ts
  src/model/CompositeNumberColumn.ts
  src/model/DateColumn.ts
  src/model/DatesColumn.ts
  src/model/DatesMapColumn.ts
  src/model/GroupColumn.ts
  src/model/HierarchyColumn.ts
  src/model/ImpositionBoxPlotColumn.ts
  src/model/ImpositionCompositeColumn.ts
  src/model/ImpositionCompositesColumn.ts
  src/model/LinkColumn.ts
  src/model/LinkMapColumn.ts
  src/model/LinksColumn.ts
  src/model/NestedColumn.ts
  src/model/NumberColumn.ts
  src/model/NumberMapColumn.ts
  src/model/NumbersColumn.ts
  src/model/OrdinalColumn.ts
  src/model/SetColumn.ts
  src/model/StringColumn.ts
  src/model/StringMapColumn.ts
  src/model/StringsColumn.ts
  src/provider/ACommonDataProvider.ts
  src/provider/ADataProvider.ts
  src/provider/interfaces.ts
  src/ui/EngineRenderer.ts
  src/ui/dialogs/ADialog.ts
  src/ui/dialogs/AddonDialog.ts
  src/ui/dialogs/GroupDialog.ts
  src/ui/dialogs/MoreColumnOptionsDialog.ts
  src/ui/dialogs/SortDialog.ts
  src/ui/header.ts
  src/ui/interfaces.ts
  src/ui/panel/SidePanelEntryVis.ts
  src/ui/toolbar.ts
Labels: lineup: v4, type: feature
