Repository lineupjs/lineupjs, pull requests merged in 2020-06, with the labels that each got.

#333 Fix typo in LineUp htmlwidget
  README.md
Labels: lineup: v4, type: docs

#334 Filter all or some categories in `SetColumn`
  src/model/ICategoricalColumn.ts
  src/model/SetColumn.ts
  src/model/internalCategorical.ts
  src/renderer/CategoricalCellRenderer.ts
  src/ui/dialogs/CategoricalFilterDialog.ts
Labels: lineup: v4, type: feature

#341 Clear filter when string column filter is null and filterMissing: false
  src/renderer/StringCellRenderer.ts
Labels: lineup: v4, release: minor, type: bug

#339 Fix type exports
  .gitignore
  package-lock.json
  src/provider/interfaces.ts
  src/renderer/AAggregatedGroupRenderer.ts
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/ActionRenderer.ts
  src/renderer/AggregateGroupRenderer.ts
  src/renderer/AnnotationRenderer.ts
  src/renderer/BarCellRenderer.ts
  src/renderer/BooleanCellRenderer.ts
  src/renderer/BoxplotCellRenderer.ts
  src/renderer/BrightnessCellRenderer.ts
  src/renderer/CategoricalCellRenderer.ts
  src/renderer/CategoricalHeatmapCellRenderer.ts
  src/renderer/CategoricalStackedDistributionlCellRenderer.ts
  src/renderer/CircleCellRenderer.ts
  src/renderer/DateCellRenderer.ts
  src/renderer/DateHistogramCellRenderer.ts
  src/renderer/DefaultCellRenderer.ts
  src/renderer/DotCellRenderer.ts
  src/renderer/GroupCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/ImageCellRenderer.ts
  src/renderer/InterleavingCellRenderer.ts
  src/renderer/LinkCellRenderer.ts
  src/renderer/LinkMapCellRenderer.ts
  src/renderer/LoadingCellRenderer.ts
  src/renderer/MapBarCellRenderer.ts
  src/renderer/MultiLevelCellRenderer.ts
  src/renderer/RankCellRenderer.ts
  src/renderer/SelectionRenderer.ts
  src/renderer/SetCellRenderer.ts
  src/renderer/SparklineCellRenderer.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/TableCellRenderer.ts
  src/renderer/UpSetCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/renderer/utils.ts
Labels: lineup: v4

#342 Add new lines between checkbox and text for equal spacing
  src/renderer/StringCellRenderer.ts
  src/ui/dialogs/SearchDialog.ts
  src/ui/dialogs/StringFilterDialog.ts
Labels: lineup: v4

#343 Unify font style + size for checkboxes in dialogs
  src/styles/_common.scss
  src/styles/_dialogs.scss
Labels: lineup: v4

#345 Replace `overflow-x` with `overflow` to avoid scrollbars in stacked bars
  src/renderer/MultiLevelCellRenderer.ts
Labels: lineup: v4, type: bug

#362 Fix categorical filter comparison
  src/model/internalCategorical.ts
Labels: release: patch, type: bug

#363 restore grouping aggregations
  cypress/integration/restore_ranking.spec.ts
  src/model/Column.ts
  src/model/StringColumn.ts
Labels: release: patch, type: bug

#364 Improved aggregation tracking
  cypress/integration/pr275_sort_group_by.spec.ts
  cypress/integration/restore_aggregation_state.spec.ts
  cypress/integration/restore_ranking.spec.ts
  cypress/integration/utils/data.ts
  cypress/integration/utils/ui.ts
  src/model/Ranking.ts
  src/model/internal.ts
  src/provider/ADataProvider.ts
  src/provider/internal.ts
  src/renderer/AggregateGroupRenderer.ts
  src/styles/_common.scss
Labels: release: major, type: feature

#353 Minor modification to the AggregateGroupRenderer summary implementation
  src/provider/ADataProvider.ts
  src/renderer/AggregateGroupRenderer.ts
Labels: release: minor, type: bug

#370 Fix centering of rank
  src/styles/renderer/_rank.scss
Labels: release: patch, type: bug

#371 Fix group clipping
  src/renderer/GroupCellRenderer.ts
  src/styles/renderer/_aggregate.scss
  src/styles/renderer/_string.scss
  src/ui/EngineRanking.ts
Labels: release: patch, type: bug
