Repository lineupjs/lineupjs, pull requests merged in 2020-01, with the labels that each got.

#218 Group by string value in StringColumn (V4)
  demo/string_grouping.html
  src/model/LinkColumn.ts
  src/model/StringColumn.ts
  src/ui/dialogs/groupString.ts
Labels: lineup: v4, type: feature

#216 Fixed grouping of LinkColumn and exported required interfaces
  src/model/LinkColumn.ts
  src/model/StringColumn.ts
  src/model/index.ts
Labels: lineup: v3, release: patch, type: bug

#210 Export renderer classes and improve typings for renderer functio…
  src/renderer/AAggregatedGroupRenderer.ts
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/ActionRenderer.ts
  src/renderer/AggregateGroupRenderer.ts
  src/renderer/AnnotationRenderer.ts
  src/renderer/BarCellRenderer.ts
  src/renderer/BooleanCellRenderer.ts
  src/renderer/BoxplotCellRenderer.ts
  src/renderer/BrightnessCellRenderer.ts
  src/renderer/CategoricalCellRenderer.ts
  src/renderer/CategoricalHeatmapCellRenderer.ts
  src/renderer/CategoricalStackedDistributionlCellRenderer.ts
  src/renderer/CircleCellRenderer.ts
  src/renderer/DateCellRenderer.ts
  src/renderer/DefaultCellRenderer.ts
  src/renderer/DotCellRenderer.ts
  src/renderer/GroupCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/ImageCellRenderer.ts
  src/renderer/InterleavingCellRenderer.ts
  src/renderer/LinkCellRenderer.ts
  src/renderer/LinkMapCellRenderer.ts
  src/renderer/LoadingCellRenderer.ts
  src/renderer/MapBarCellRenderer.ts
  src/renderer/MultiLevelCellRenderer.ts
  src/renderer/RankCellRenderer.ts
  src/renderer/SelectionRenderer.ts
  src/renderer/SparklineCellRenderer.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/TableCellRenderer.ts
  src/renderer/UpSetCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/renderer/index.ts
Labels: lineup: v3, release: patch

#234 Release 3.3.0
  demo/script_column.html
  demo/small_numbers.html
  demo/string_grouping.html
  package-lock.json
  package.json
  src/model/LinkColumn.ts
  src/model/ScriptColumn.ts
  src/model/StringColumn.ts
  src/model/index.ts
  src/renderer/AAggregatedGroupRenderer.ts
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/ActionRenderer.ts
  src/renderer/AggregateGroupRenderer.ts
  src/renderer/AnnotationRenderer.ts
  src/renderer/BarCellRenderer.ts
  src/renderer/BooleanCellRenderer.ts
  src/renderer/BoxplotCellRenderer.ts
  src/renderer/BrightnessCellRenderer.ts
  src/renderer/CategoricalCellRenderer.ts
  src/renderer/CategoricalHeatmapCellRenderer.ts
  src/renderer/CategoricalStackedDistributionlCellRenderer.ts
  src/renderer/CircleCellRenderer.ts
  src/renderer/DateCellRenderer.ts
  src/renderer/DefaultCellRenderer.ts
  src/renderer/DotCellRenderer.ts
  src/renderer/GroupCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/ImageCellRenderer.ts
  src/renderer/InterleavingCellRenderer.ts
  src/renderer/LinkCellRenderer.ts
  src/renderer/LinkMapCellRenderer.ts
  src/renderer/LoadingCellRenderer.ts
  src/renderer/MapBarCellRenderer.ts
  src/renderer/MultiLevelCellRenderer.ts
  src/renderer/RankCellRenderer.ts
  src/renderer/SelectionRenderer.ts
  src/renderer/SparklineCellRenderer.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/TableCellRenderer.ts
  src/renderer/UpSetCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/renderer/index.ts
  src/renderer/utils.ts
  src/styles/renderer/_bar.scss
  src/styles/renderer/_rank.scss
  src/ui/dialogs/StringFilterDialog.ts
  src/ui/dialogs/groupString.ts
Labels: lineup: v3, release: minor
