Repository lineupjs/lineupjs, pull requests merged in 2020-04, with the labels that each got.

#207 Export renderer in own namespace
  src/renderer/ANumbersCellRenderer.ts
  src/renderer/ActionRenderer.ts
  src/renderer/AggregateGroupRenderer.ts
  src/renderer/AnnotationRenderer.ts
  src/renderer/BarCellRenderer.ts
  src/renderer/BooleanCellRenderer.ts
  src/renderer/BoxplotCellRenderer.ts
  src/renderer/BrightnessCellRenderer.ts
  src/renderer/CategoricalCellRenderer.ts
  src/renderer/CategoricalHeatmapCellRenderer.ts
  src/renderer/CategoricalStackedDistributionlCellRenderer.ts
  src/renderer/CircleCellRenderer.ts
  src/renderer/DateCellRenderer.ts
  src/renderer/DateHistogramCellRenderer.ts
  src/renderer/DefaultCellRenderer.ts
  src/renderer/DotCellRenderer.ts
  src/renderer/GroupCellRenderer.ts
  src/renderer/HeatmapCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/ImageCellRenderer.ts
  src/renderer/InterleavingCellRenderer.ts
  src/renderer/LinkCellRenderer.ts
  src/renderer/LinkMapCellRenderer.ts
  src/renderer/LoadingCellRenderer.ts
  src/renderer/MapBarCellRenderer.ts
  src/renderer/MultiLevelCellRenderer.ts
  src/renderer/RankCellRenderer.ts
  src/renderer/SelectionRenderer.ts
  src/renderer/SetCellRenderer.ts
  src/renderer/SparklineCellRenderer.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/TableCellRenderer.ts
  src/renderer/UpSetCellRenderer.ts
  src/renderer/VerticalBarCellRenderer.ts
  src/renderer/histogram.ts
  src/renderer/index.ts
Labels: lineup: v4, release: minor

#288 Fix reset of the filter histogram
  src/renderer/HistogramCellRenderer.ts
  src/ui/dialogs/NumberFilterDialog.ts
Labels: lineup: v4

#287 Fix reset of group and sort dialog
  src/ui/dialogs/GroupDialog.ts
  src/ui/dialogs/SortDialog.ts
Labels: lineup: v4

#280 Cypress e2e testing
  .circleci/config.yml
  README.md
  cypress.json
  cypress/.gitignore
  cypress/index.html
  cypress/integration/big.spec.ts
  cypress/integration/builder.spec.ts
  cypress/integration/builder2.spec.ts
  cypress/integration/pr275_sort_group_by.spec.ts
  cypress/integration/utils/data.ts
  cypress/integration/utils/lineup.ts
  cypress/integration/utils/ui.ts
  cypress/plugins/cy-ts-preprocessor.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  demo/cypress/index.html
  package-lock.json
  package.json
  src/builder/DataBuilder.ts
  src/builder/RankingBuilder.ts
  src/builder/column/index.ts
  tests/builder/DataBuilder.spec.ts
  tsconfig.json
  tsconfig.prod.json
Labels: lineup: v4

#289 Fix color mapping reset + improve color mapping dialog
  cypress/integration/pr289_color_mapping_reset.spec.ts
  cypress/integration/utils/ui.ts
  src/provider/ADataProvider.ts
  src/provider/interfaces.ts
  src/styles/_dialogs.scss
  src/ui/dialogs/ColorMappingDialog.ts
  src/ui/toolbar.ts
Labels: lineup: v4

#294 Update browserlist and issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
Labels: lineup: v4

#298 Fix CircleCI error by updating the cache key
  .circleci/config.yml
Labels: lineup: v4

#292 Improve data mapping dialog
  cypress/integration/pr292_data_mapping.spec.ts
  src/styles/_dialogs.scss
  src/styles/_mappingeditor.scss
  src/styles/_vars.scss
  src/styles/engine/_index.scss
  src/ui/dialogs/MappingDialog.ts
  src/ui/dialogs/MappingLineDialog.ts
Labels: lineup: v4

#296 Optimize filter dialogs
  src/renderer/DateHistogramCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/histogram.ts
  src/ui/dialogs/ADialog.ts
  src/ui/dialogs/DateFilterDialog.ts
  src/ui/dialogs/DialogManager.ts
  src/ui/dialogs/MappingDialog.ts
  src/ui/dialogs/NumberFilterDialog.ts
Labels: lineup: v4

#310 Fix missing values and overflow of aggregated groups in link renderer
  demo/missing.html
  src/renderer/LinkCellRenderer.ts
  src/styles/renderer/_string.scss
Labels: lineup: v4

#317 Update node-sass dependency
  package-lock.json
  package.json
Labels: lineup: v4, type: technical debt
