Repository lineupjs/lineupjs, pull requests merged in 2020-05, with the labels that each got.

#321 Update Cypress dependency to 4.5.0
  package-lock.json
  package.json
Labels: lineup: v4, priority: high, type: technical debt

#324 Add tooltip for strings column
  src/renderer/DefaultCellRenderer.ts
Labels: lineup: v4

#328 Auto close menu dialogs
  cypress/integration/utils/ui.ts
  src/ui/dialogs/ADialog.ts
  src/ui/dialogs/DialogManager.ts
  src/ui/dialogs/MoreColumnOptionsDialog.ts
  src/ui/dialogs/MoreRankingOptionsDialog.ts
Labels: lineup: v4

#329 Fix frozen column shift
  demo/frozen.html
  src/styles/engine/_header.scss
  src/styles/engine/_row.scss
Labels: lineup: v4, type: bug
