Repository lineupjs/lineupjs, pull requests merged in 2021-07, with the labels that each got.

#448 feat: add summary to column adder
  src/styles/panel/_search.scss
  src/ui/panel/Hierarchy.ts
  src/ui/panel/SearchBox.ts
  src/ui/panel/SidePanel.ts
Labels: type: feature

#454 Missing value for StackColumn if at least one child value is missing
  src/model/StackColumn.ts
Labels: priority: high, type: bug

#416 string stats and histogram
  src/internal/math.ts
  src/internal/mathInterfaces.ts
  src/internal/worker.ts
  src/provider/DirectRenderTasks.ts
  src/provider/LocalDataProvider.ts
  src/provider/RemoteDataProvider.ts
  src/provider/ScheduledTasks.ts
  src/provider/tasks.ts
  src/renderer/StringCellRenderer.ts
  src/renderer/StringHistogramCellRenderer.ts
  src/renderer/index.ts
  src/renderer/interfaces.ts
  src/renderer/rendererClasses.ts
  src/renderer/rendererUtils.ts
  src/renderer/renderers.ts
  src/styles/panel/_entry.scss
  src/ui/dialogs/StringFilterDialog.ts
  src/ui/panel/SidePanel.ts
  src/ui/panel/SidePanelRanking.ts
  src/ui/toolbar.ts
Labels: type: feature

#473 ci: update yarn.lock and add .pnp.cjs from yarn@3.0.0
  .pnp.cjs
  .prettierignore
  package.json
  yarn.lock
Labels: chore, dependencies

#462 Confirm dialog with click on background
  src/config.ts
Labels: type: feature
