Repository lineupjs/lineupjs, pull requests merged in 2022-08, with the labels that each got.

#588 fix: text filter no wrap and overflow
  src/styles/renderer/_string.scss
Labels: type: bug

#590 feat: add clear button to selection column
  src/model/SelectionColumn.ts
  src/styles/header/_toolbar.scss
  src/styles/panel/_index.scss
  src/ui/panel/SidePanel.ts
  src/ui/toolbar.ts
Labels: type: feature

#586 fix: don't cross histogram filter
  src/renderer/DateHistogramCellRenderer.ts
  src/renderer/HistogramCellRenderer.ts
  src/renderer/histogram.ts
Labels: type: bug

#589 use background selection indicator
  src/model/Column.ts
  src/styles/_vars.scss
  src/styles/engine/_header.scss
  src/styles/engine/_row.scss
  src/styles/header/_toolbar.scss
  src/styles/index.ts
  src/styles/panel/_index.scss
Labels: type: feature

#595 Fix minor typo in README
  README.md
Labels: type: docs
