Repository lineupjs/lineupjs, pull requests merged in 2022-07, with the labels that each got.

#576 Set `font-family` to Font Awesome 6 when using external FA
  src/styles/icons/_index.scss
Labels: type: bug, release: patch

#580 Add option for custom instance id
  cypress/integration/custom_instance_id.spec.ts
  src/builder/LineUpBuilder.ts
  src/config.ts
  src/ui/EngineRenderer.ts
  src/ui/dialogs/CompositeChildrenDialog.ts
Labels: type: feature, lineup: v4

#582 upgrade dependencies
  .github/workflows/ci.yml
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  README.md
  cypress.config.js
  cypress.json
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: chore

#585 Allow removal of selection columns from ranking + fix error in scheduler.ts
  src/internal/scheduler.ts
  src/model/SelectionColumn.ts
Labels: type: bug
